services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PORT=3001
    depends_on: []

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    restart: always
    expose:
      - "80"
    depends_on:
      - api
