FROM nginx:alpine
COPY dashboard-leads.html /usr/share/nginx/html/
COPY relatorio-ia.html /usr/share/nginx/html/
COPY contatos.html /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
